language: generic
sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - COLLECT_ERROR= 1

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t razear/mega-electric-nginx:latest -t razear/mega-electric-nginx:$SHA -f Dockerfile .
  - docker push razear/mega-electric-nginx:latest
  - docker push razear/mega-electric-nginx:$SHA


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main